improvement: implemented {tax_rate_selection} for code unification
chilek/lms pull request #2276
Opened 2022-06-22 15:47 UTC by interduo

2022-06-30 16:41 UTC, interduo commented
@chilek wypuścisz to?

2022-07-08 16:23 UTC, chilek requested changes

2022-07-08 16:23 UTC, chilek commented on lib/SmartyPlugins/function.tax_rate_selection.php
> +    $icon = '<i class="' . (strpos($params['icon'], 'lms-ui-icon-') === 0 ? $params['icon'] : 'lms-ui-icon-' . $params['icon']) . '"></i>';
Dlaczego zawsze musimy podawać paraetr **icon**? Nie można jakiejś gotowej ikony brać, gdy nie podano tego parametru?

2022-07-11 11:06 UTC, interduo commented on lib/SmartyPlugins/function.tax_rate_selection.php
> +    $icon = '<i class="' . (strpos($params['icon'], 'lms-ui-icon-') === 0 ? $params['icon'] : 'lms-ui-icon-' . $params['icon']) . '"></i>';
Można ależ proszę https://github.com/chilek/lms/pull/2276/commits/6a0e61aae57645e78eb97d33dd2fbc8f3c16e5f0.

2022-07-20 16:44 UTC, chilek commented
Dlaczego nie poprzez funkcję statyczną w LMSSmartyPlugins i tylko odwołanie z poziomu function.tax_rate_selection.php?
Potem ciężko będzie tego użyć w innych funkcjach smarty.

2022-07-27 12:44 UTC, interduo commented
@chilek wypuścisz to?

2022-07-27 15:17 UTC, merged

2022-07-27 15:17 UTC, chilek commented
10q